"""removing unique constraint

Revision ID: 2c0b9512e1e6
Revises: e50fea6560d6
Create Date: 2024-05-06 19:21:14.256220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0b9512e1e6'
down_revision = 'e50fea6560d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzle', schema=None) as batch_op:
        batch_op.drop_constraint('uq_logic_master', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzle', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_logic_master', ['logic_master_url'])

    # ### end Alembic commands ###
