"""adding size

Revision ID: 76d78c257363
Revises: 81fcef787617
Create Date: 2024-05-04 18:54:50.873680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d78c257363'
down_revision = '81fcef787617'
branch_labels = None
depends_on = None


def upgrade():
    # Create a new temporary table with the desired schema
    op.create_table('_alembic_tmp_puzzle_solve',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('puzzle_id', sa.Integer(), nullable=True),
        sa.Column('row', sa.Integer(), nullable=True),
        sa.Column('column', sa.Integer(), nullable=True),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.Column('insert_time', sa.DateTime(), nullable=True)
    )
    
    # Copy data from the old table to the new temporary table
    op.execute(
        'INSERT INTO _alembic_tmp_puzzle_solve (id, user_id, puzzle_id, "row", "column", value, insert_time) '
        'SELECT id, user_id, puzzle_id, "row", "column", value, insert_time FROM puzzle_solve'
    )

    # Drop the original table
    op.drop_table('puzzle_solve')

    # Rename the temporary table to the original name
    op.rename_table('_alembic_tmp_puzzle_solve', 'puzzle_solve')    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sudoku_puzzle', schema=None) as batch_op:
        batch_op.drop_column('standard')
        batch_op.drop_column('size')

    with op.batch_alter_table('puzzle_solve', schema=None) as batch_op:
        batch_op.alter_column('insert_time',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
